-- --------------------------------------------
-- T_MOCA_USERS
-- --------------------------------------------

CREATE TABLE IF NOT EXISTS MOCA.T_MOCA_USERS(
	id                          BIGINT GENERATED BY DEFAULT AS IDENTITY UNIQUE NOT NULL,
    user_nid                    VARCHAR(21) UNIQUE NOT NULL,
	usr_tx_name                 VARCHAR(45) NOT NULL,
	usr_tx_first_surname        VARCHAR(45) NOT NULL,
	usr_tx_second_surname       VARCHAR(45) NOT NULL,
	usr_dt_birthdate            TIMESTAMP NOT NULL,
    usr_dt_created_at           TIMESTAMP NOT NULL,
    usr_dt_updated_at           TIMESTAMP NOT NULL,
    usr_st_is_active            BOOLEAN NOT NULL DEFAULT TRUE,
    usr_fk_gender_id            VARCHAR(32) NOT NULL,
	PRIMARY KEY(id)
);

-- INDEX --

CREATE INDEX I_USER_NID ON MOCA.T_MOCA_USERS(user_nid);

-- --------------------------------------------
-- T_MOCA_ACCOUNTS
-- --------------------------------------------

CREATE TABLE IF NOT EXISTS MOCA.T_MOCA_ACCOUNTS(
    id                          BIGINT GENERATED BY DEFAULT AS IDENTITY UNIQUE NOT NULL,
    account_nid                 VARCHAR(21) UNIQUE NOT NULL,
    acc_tx_nickname             VARCHAR(45) UNIQUE NOT NULL,
    acc_tx_email                VARCHAR(255) UNIQUE NOT NULL,
    acc_tx_backup_email         VARCHAR(255),
    acc_tx_password             VARCHAR(255) NOT NULL,
    acc_tx_mobile_ext           VARCHAR(10),
    acc_tx_mobile_phone         VARCHAR(15) NOT NULL,
    acc_json_images             JSONB,
    acc_dt_created_at           TIMESTAMP NOT NULL,
    acc_dt_updated_at           TIMESTAMP NOT NULL,
    acc_st_is_active            BOOLEAN NOT NULL DEFAULT TRUE,
    acc_fk_role_id              SMALLINT NOT NULL,
    acc_fk_status_id            VARCHAR(45) NOT NULL,
    PRIMARY KEY(id)
);

-- INDEX --

CREATE INDEX I_ACCOUNT_NID ON MOCA.T_MOCA_ACCOUNTS(account_nid);

-- --------------------------------------------
-- T_MOCA_ADDRESSES
-- --------------------------------------------

CREATE TABLE IF NOT EXISTS MOCA.T_MOCA_ADDRESSES(
    id                          BIGINT GENERATED BY DEFAULT AS IDENTITY UNIQUE NOT NULL,
    address_nid                 VARCHAR(21) UNIQUE NOT NULL,
    adr_tx_street               VARCHAR(255) UNIQUE,
    adr_tx_number               VARCHAR(10) NOT NULL,
    adr_tx_zip_code             VARCHAR(20),
    adr_dt_created_at           TIMESTAMP NOT NULL,
    adr_dt_updated_at           TIMESTAMP NOT NULL,
    adr_st_is_active            BOOLEAN NOT NULL DEFAULT TRUE,
    adr_fk_city_id              SMALLINT NOT NULL,
    PRIMARY KEY(id)
);

-- INDEX --

CREATE INDEX I_ADDRESS_NID ON MOCA.T_MOCA_ADDRESSES(address_nid);

-- --------------------------------------------
-- T_MOCA_USERS_ADDRESSES_HUB
-- --------------------------------------------

CREATE TABLE IF NOT EXISTS MOCA.T_MOCA_USERS_ADDRESSES_HUB(
    id                      BIGINT GENERATED BY DEFAULT AS IDENTITY UNIQUE NOT NULL,
    user_id                 BIGINT NOT NULL,
    user_nid                VARCHAR(21) NOT NULL,
    address_id              BIGINT NOT NULL,
    address_nid             VARCHAR(21) NOT NULL,
    PRIMARY KEY(id)
);

-- INDEX --

CREATE INDEX I_HUB_USER_NID ON MOCA.T_MOCA_USERS_ADDRESSES_HUB(user_nid);
CREATE INDEX I_HUB_ACCOUNT_NID ON MOCA.T_MOCA_USERS_ADDRESSES_HUB(address_nid);

-- --------------------------------------------
-- CONSTRAINTS
-- --------------------------------------------

ALTER TABLE MOCA.T_MOCA_USERS
	ADD CONSTRAINT FK01_T_MOCA_USERS_TO_GENDERS
		FOREIGN KEY(usr_fk_gender_id)
		REFERENCES MOCA.T_SHR_GENDERS(gender_id);

ALTER TABLE MOCA.T_MOCA_USERS
	ADD CONSTRAINT FK02_T_MOCA_USERS_TO_ACCOUNTS
		FOREIGN KEY(user_nid)
		REFERENCES MOCA.T_MOCA_ACCOUNTS(account_nid);

--

ALTER TABLE MOCA.T_MOCA_ACCOUNTS
	ADD CONSTRAINT FK01_T_MOCA_ACCOUNTS_TO_ROLES
		FOREIGN KEY(acc_fk_role_id)
		REFERENCES MOCA.T_MOCA_ROLES(role_id);

--

ALTER TABLE MOCA.T_MOCA_ADDRESSES
	ADD CONSTRAINT FK02_T_MOCA_ADDRESSES_TO_CITY
		FOREIGN KEY(adr_fk_city_id)
		REFERENCES MOCA.T_SHR_CITIES(city_id);

--

ALTER TABLE MOCA.T_MOCA_USERS_ADDRESSES_HUB
	ADD CONSTRAINT FK01_T_HUB_TO_USERS
		FOREIGN KEY(user_id)
		REFERENCES MOCA.T_MOCA_USERS(id);

ALTER TABLE MOCA.T_MOCA_USERS_ADDRESSES_HUB
	ADD CONSTRAINT FK02_T_HUB_TO_ADDRESS
		FOREIGN KEY(address_id)
		REFERENCES MOCA.T_MOCA_ADDRESSES(id);

-- --------------------------------------------
-- INSERTS
-- --------------------------------------------

INSERT INTO MOCA.T_MOCA_ACCOUNTS 
    (account_id, acc_tx_nickname, acc_tx_email, acc_tx_backup_email, acc_tx_password, acc_tx_mobile_phone, acc_tx_status, acc_json_images, acc_dt_created_at, acc_dt_updated_at, acc_st_is_active, acc_fk_role_id)
VALUES
    ('sS-qYumQrNytg8mt9FZaC', 'ymoyamac', 'yael.moya@email.com', 'ymoyamac@correo.com', 'Passw0rd!', '5551234567', 'ACTIVE', '{"images": [{"id": 1,"url": "https://image-1.jpg","description": "User image 1"}]}'::jsonb, NOW(), NOW(), TRUE, 'ADMIN_ROLE')
    --(2, 'programacionats', 'ale_taboa@email.com', 'astaboa@correo.com', 'Passw0rd!', '5572212417', 'ACTIVE', NULL, NOW(), NOW(), TRUE),
    --(3, 'sarori', 'toniduran@email.com', 'spainduran@correo.com', 'Passw0rd!', '5558182187',, 'ACTIVE', NULL, NOW(), NOW(), TRUE),
	--(4, 'johndoe', 'john.doe@example.com', 'john.backup@example.com', 'password123', '5551234567', 'ACTIVE', NULL, NOW(), NOW(), TRUE),
    --(5, 'karlahdz', 'karla.hernandez@example.com', NULL, 'Passw0rd!', '5551234569', 'ACTIVE', NULL, NOW(), NOW(), FALSE),
    --(6, 'susana.cuevas', 'susana.cuevas.escobar@example.com', 'susana.backup@example.com', 'Passw0rd!', '5551234572', 'ACTIVE', NULL, NOW(), NOW(), FALSE);

INSERT INTO MOCA.T_MOCA_USERS 
    (user_id, usr_tx_name, usr_tx_first_surname, usr_tx_second_surname, usr_dt_birthdate, usr_dt_created_at, usr_dt_updated_at, usr_st_is_active, usr_fk_gender_id)
VALUES
    ('sS-qYumQrNytg8mt9FZaC', 'Yael Jaffar', 'Moya', 'Macías', '1999-12-29', NOW(), NOW(), TRUE, 'MALE')
    --(2, 'Alejandro', 'Sanchez', 'Taboada', '1990-01-15', NOW(), NOW(), TRUE, 1, 2, 2),
    --(3, 'Antonio', 'Sarosi', 'Spain', '1987-04-19', NOW(), NOW(), TRUE, 1, 2, 3),
    --(4, 'John', 'Doe', 'Smith', '1990-01-15', NOW(), NOW(), TRUE, 1, 2, 4),
    --(5, 'Karla', 'Hernandez', 'Hernandez', '1985-07-23', NOW(), NOW(), TRUE, 2, 3, 5),
    --(6, 'Susana', 'Cuevas', 'Escobar', '1988-04-09', NOW(), NOW(), TRUE, 2, 4, 6);

INSERT INTO MOCA.T_MOCA_ADDRESSES 
    (address_id, adr_tx_street, adr_tx_number, adr_tx_zip_code, adr_dt_created_at, adr_dt_updated_at, adr_st_is_active, adr_fk_country_id)
VALUES
    ('8UvOfQW4oAEp9KrzL5FIU', '150 Sunny Isles Blvd', '28', '33160', NOW(), NOW(), TRUE, 484)
    --(2, 'Av. Central de puente nuevo', '23B', '23456', NOW(), NOW(), TRUE, 9, 8),
    --(3, 'Madrid, Paseo de la Castellana', '8', '34567', NOW(), NOW(), FALSE, 3, 9),
    --(4, '1 Maple Road', '15C', '45678', NOW(), NOW(), TRUE, 2, 1),
    --(5, '5 de mayo', '12D', '56789', NOW(), NOW(), TRUE, 1, 1),
    --(6, 'Insurgentes sur', '3', '67890', NOW(), NOW(), TRUE, 1, 1);

INSERT INTO MOCA.T_MOCA_USERS_ADDRESSES_HUB
	(id, user_id, address_id)
VALUES
	(1, 'sS-qYumQrNytg8mt9FZaC', '8UvOfQW4oAEp9KrzL5FIU');

-- --------------------------------------------
-- SELECTS
-- --------------------------------------------

SELECT T_MOCA_USERS.user_id,
	T_MOCA_USERS.usr_tx_name,
	T_MOCA_USERS.usr_tx_first_surname,
	T_MOCA_USERS.usr_tx_second_surname,
	T_MOCA_USERS.usr_dt_birthdate,
	T_MOCA_USERS.usr_st_is_active,
	T_MOCA_ACCOUNTS.acc_tx_nickname,
	T_MOCA_ACCOUNTS.acc_tx_email,
	T_MOCA_ACCOUNTS.acc_tx_backup_email,
	T_MOCA_ACCOUNTS.acc_tx_password,
	T_MOCA_ACCOUNTS.acc_tx_mobile_phone,
	T_MOCA_ACCOUNTS.acc_tx_status,
	T_MOCA_ACCOUNTS.acc_json_images,
	T_MOCA_ADDRESSES.address_id,
	T_MOCA_ADDRESSES.adr_tx_street,
	T_MOCA_ADDRESSES.adr_tx_number,
	T_MOCA_ADDRESSES.adr_tx_zip_code,
	T_SHR_CITIES.cty_tx_name,
	T_SHR_COUNTRIES.ctry_tx_name,
	T_MOCA_ROLES.role_id
FROM T_MOCA_USERS
INNER JOIN T_MOCA_ACCOUNTS ON T_MOCA_USERS.user_id = T_MOCA_ACCOUNTS.account_id
INNER JOIN T_MOCA_USERS_ADDRESSES_HUB ON T_MOCA_USERS.user_id = T_MOCA_USERS_ADDRESSES_HUB.user_id
INNER JOIN T_MOCA_ADDRESSES ON T_MOCA_USERS_ADDRESSES_HUB.address_id = T_MOCA_ADDRESSES.address_id
INNER JOIN T_MOCA_ROLES ON T_MOCA_ACCOUNTS.acc_fk_role_id = T_MOCA_ROLES.role_id
INNER JOIN T_SHR_CITIES ON T_MOCA_ADDRESSES.adr_fk_city_id = T_SHR_CITIES.city_id
INNER JOIN T_SHR_COUNTRIES ON T_SHR_CITIES.cty_fk_country_id = T_SHR_COUNTRIES.country_id;

-- --------------------------------------------
-- ALTERS
-- --------------------------------------------

ALTER TABLE T_MOCA_USERS_ADDRESSES_HUB
	ALTER COLUMN user_id TYPE varchar(21);

ALTER TABLE T_MOCA_USERS
	ALTER COLUMN user_id TYPE varchar(21);