--https://www.iban.com/country-codes
-- --------------------------------------------
-- T_SHR_COUNTRIES
-- --------------------------------------------

CREATE TABLE IF NOT EXISTS MOCA.T_SHR_COUNTRIES(
	country_id              SMALLINT GENERATED BY DEFAULT AS IDENTITY UNIQUE NOT NULL,
	ctry_tx_name            VARCHAR(255) UNIQUE NOT NULL,
	ctry_tx_abbrevation     VARCHAR(32) UNIQUE NOT NULL,
    ctry_dt_created_at      TIMESTAMP NOT NULL,
    ctry_dt_updated_at      TIMESTAMP NOT NULL,
	ctry_st_is_active       BOOLEAN NOT NULL DEFAULT TRUE,
	PRIMARY KEY(country_id)
);

-- --------------------------------------------
-- INSERTS
-- --------------------------------------------

INSERT INTO MOCA.T_SHR_COUNTRIES VALUES (484, 'México', 'MX', NOW(), NOW(), true);
-- INSERT INTO T_SHR_COUNTRIES VALUES (2, 'Canada', 'CAN', 124, now(), now(), true);
-- INSERT INTO T_SHR_COUNTRIES VALUES (3, 'España', 'ESP', 724, now(), now(), true);
-- INSERT INTO T_SHR_COUNTRIES VALUES (4, 'Chile', 'CHL', 152, now(), now(), true);
-- INSERT INTO T_SHR_COUNTRIES VALUES (5, 'Colombia', 'CO', 170, now(), now(), true);
-- INSERT INTO T_SHR_COUNTRIES VALUES (6, 'El Salvador', 'SV', 222, now(), now(), true);
-- INSERT INTO T_SHR_COUNTRIES VALUES (7, 'Panama', 'PAN', 591, now(), now(), true);
-- INSERT INTO T_SHR_COUNTRIES VALUES (8, 'Argentina', 'ARG', 32, now(), now(), true);
-- INSERT INTO T_SHR_COUNTRIES VALUES (9, 'Perú', 'PR', 604, now(), now(), true);

-- --------------------------------------------
-- SELECTS
-- --------------------------------------------

SELECT country_id AS id,
	ctry_tx_name as ctry_tx_name,
    ctry_tx_abbrevation AS abbrevation,
    ctry_dt_created_at AS created_at,
    ctry_dt_updated_at AS updated_at,
    ctry_st_is_active AS is_active
FROM MOCA.T_SHR_COUNTRIES;
